# .claude-sandbox.yaml — extra volume mounts for the sandbox container
#
# Place this file in your project root (next to .env.claude-sandbox).
# Requires 'yq' to be installed on the host.
#
# Each mount entry has:
#   host:      absolute path on the host (required)
#   container: absolute path inside the container (required)
#   writable:  boolean, default false (mounts :ro unless true)

mounts: []
  # - host: /home/myuser/my-models/stable-diffusion
  #   container: /data/checkpoints
  #
  # - host: /home/myuser/checkpoint-sampler/samples
  #   container: /data/samples
  #   writable: true
