// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package apimocks

import (
	"context"

	"github.com/kmacmcfarlane/checkpoint-sampler/backend/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWorkflowLoader creates a new instance of MockWorkflowLoader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkflowLoader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkflowLoader {
	mock := &MockWorkflowLoader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWorkflowLoader is an autogenerated mock type for the WorkflowLoader type
type MockWorkflowLoader struct {
	mock.Mock
}

type MockWorkflowLoader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkflowLoader) EXPECT() *MockWorkflowLoader_Expecter {
	return &MockWorkflowLoader_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockWorkflowLoader
func (_mock *MockWorkflowLoader) Get(ctx context.Context, name string) (model.WorkflowTemplate, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.WorkflowTemplate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.WorkflowTemplate, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.WorkflowTemplate); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(model.WorkflowTemplate)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkflowLoader_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockWorkflowLoader_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockWorkflowLoader_Expecter) Get(ctx any, name any) *MockWorkflowLoader_Get_Call {
	return &MockWorkflowLoader_Get_Call{Call: _e.mock.On("Get", ctx, name)}
}

func (_c *MockWorkflowLoader_Get_Call) Run(run func(ctx context.Context, name string)) *MockWorkflowLoader_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkflowLoader_Get_Call) Return(workflowTemplate model.WorkflowTemplate, err error) *MockWorkflowLoader_Get_Call {
	_c.Call.Return(workflowTemplate, err)
	return _c
}

func (_c *MockWorkflowLoader_Get_Call) RunAndReturn(run func(ctx context.Context, name string) (model.WorkflowTemplate, error)) *MockWorkflowLoader_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockWorkflowLoader
func (_mock *MockWorkflowLoader) List(ctx context.Context) ([]model.WorkflowTemplate, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.WorkflowTemplate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.WorkflowTemplate, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.WorkflowTemplate); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.WorkflowTemplate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkflowLoader_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockWorkflowLoader_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockWorkflowLoader_Expecter) List(ctx any) *MockWorkflowLoader_List_Call {
	return &MockWorkflowLoader_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockWorkflowLoader_List_Call) Run(run func(ctx context.Context)) *MockWorkflowLoader_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWorkflowLoader_List_Call) Return(workflowTemplates []model.WorkflowTemplate, err error) *MockWorkflowLoader_List_Call {
	_c.Call.Return(workflowTemplates, err)
	return _c
}

func (_c *MockWorkflowLoader_List_Call) RunAndReturn(run func(ctx context.Context) ([]model.WorkflowTemplate, error)) *MockWorkflowLoader_List_Call {
	_c.Call.Return(run)
	return _c
}
