// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package apimocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockComfyUIHealthChecker creates a new instance of MockComfyUIHealthChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockComfyUIHealthChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockComfyUIHealthChecker {
	mock := &MockComfyUIHealthChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockComfyUIHealthChecker is an autogenerated mock type for the ComfyUIHealthChecker type
type MockComfyUIHealthChecker struct {
	mock.Mock
}

type MockComfyUIHealthChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockComfyUIHealthChecker) EXPECT() *MockComfyUIHealthChecker_Expecter {
	return &MockComfyUIHealthChecker_Expecter{mock: &_m.Mock}
}

// HealthCheck provides a mock function for the type MockComfyUIHealthChecker
func (_mock *MockComfyUIHealthChecker) HealthCheck(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for HealthCheck")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockComfyUIHealthChecker_HealthCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HealthCheck'
type MockComfyUIHealthChecker_HealthCheck_Call struct {
	*mock.Call
}

// HealthCheck is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockComfyUIHealthChecker_Expecter) HealthCheck(ctx any) *MockComfyUIHealthChecker_HealthCheck_Call {
	return &MockComfyUIHealthChecker_HealthCheck_Call{Call: _e.mock.On("HealthCheck", ctx)}
}

func (_c *MockComfyUIHealthChecker_HealthCheck_Call) Run(run func(ctx context.Context)) *MockComfyUIHealthChecker_HealthCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockComfyUIHealthChecker_HealthCheck_Call) Return(err error) *MockComfyUIHealthChecker_HealthCheck_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockComfyUIHealthChecker_HealthCheck_Call) RunAndReturn(run func(ctx context.Context) error) *MockComfyUIHealthChecker_HealthCheck_Call {
	_c.Call.Return(run)
	return _c
}
