// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package apimocks

import (
	"context"

	"github.com/kmacmcfarlane/checkpoint-sampler/backend/internal/service"
	mock "github.com/stretchr/testify/mock"
)

// NewMockComfyUIModelLister creates a new instance of MockComfyUIModelLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockComfyUIModelLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockComfyUIModelLister {
	mock := &MockComfyUIModelLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockComfyUIModelLister is an autogenerated mock type for the ComfyUIModelLister type
type MockComfyUIModelLister struct {
	mock.Mock
}

type MockComfyUIModelLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockComfyUIModelLister) EXPECT() *MockComfyUIModelLister_Expecter {
	return &MockComfyUIModelLister_Expecter{mock: &_m.Mock}
}

// GetModels provides a mock function for the type MockComfyUIModelLister
func (_mock *MockComfyUIModelLister) GetModels(ctx context.Context, modelType service.ComfyUIModelType) ([]string, error) {
	ret := _mock.Called(ctx, modelType)

	if len(ret) == 0 {
		panic("no return value specified for GetModels")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, service.ComfyUIModelType) ([]string, error)); ok {
		return returnFunc(ctx, modelType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, service.ComfyUIModelType) []string); ok {
		r0 = returnFunc(ctx, modelType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, service.ComfyUIModelType) error); ok {
		r1 = returnFunc(ctx, modelType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockComfyUIModelLister_GetModels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetModels'
type MockComfyUIModelLister_GetModels_Call struct {
	*mock.Call
}

// GetModels is a helper method to define mock.On call
//   - ctx context.Context
//   - modelType service.ComfyUIModelType
func (_e *MockComfyUIModelLister_Expecter) GetModels(ctx any, modelType any) *MockComfyUIModelLister_GetModels_Call {
	return &MockComfyUIModelLister_GetModels_Call{Call: _e.mock.On("GetModels", ctx, modelType)}
}

func (_c *MockComfyUIModelLister_GetModels_Call) Run(run func(ctx context.Context, modelType service.ComfyUIModelType)) *MockComfyUIModelLister_GetModels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 service.ComfyUIModelType
		if args[1] != nil {
			arg1 = args[1].(service.ComfyUIModelType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockComfyUIModelLister_GetModels_Call) Return(strings []string, err error) *MockComfyUIModelLister_GetModels_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockComfyUIModelLister_GetModels_Call) RunAndReturn(run func(ctx context.Context, modelType service.ComfyUIModelType) ([]string, error)) *MockComfyUIModelLister_GetModels_Call {
	_c.Call.Return(run)
	return _c
}
