// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package apimocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPingableConn creates a new instance of MockPingableConn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPingableConn(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPingableConn {
	mock := &MockPingableConn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPingableConn is an autogenerated mock type for the PingableConn type
type MockPingableConn struct {
	mock.Mock
}

type MockPingableConn_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPingableConn) EXPECT() *MockPingableConn_Expecter {
	return &MockPingableConn_Expecter{mock: &_m.Mock}
}

// WriteControl provides a mock function for the type MockPingableConn
func (_mock *MockPingableConn) WriteControl(messageType int, data []byte, deadline time.Time) error {
	ret := _mock.Called(messageType, data, deadline)

	if len(ret) == 0 {
		panic("no return value specified for WriteControl")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int, []byte, time.Time) error); ok {
		r0 = returnFunc(messageType, data, deadline)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPingableConn_WriteControl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteControl'
type MockPingableConn_WriteControl_Call struct {
	*mock.Call
}

// WriteControl is a helper method to define mock.On call
//   - messageType int
//   - data []byte
//   - deadline time.Time
func (_e *MockPingableConn_Expecter) WriteControl(messageType any, data any, deadline any) *MockPingableConn_WriteControl_Call {
	return &MockPingableConn_WriteControl_Call{Call: _e.mock.On("WriteControl", messageType, data, deadline)}
}

func (_c *MockPingableConn_WriteControl_Call) Run(run func(messageType int, data []byte, deadline time.Time)) *MockPingableConn_WriteControl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPingableConn_WriteControl_Call) Return(err error) *MockPingableConn_WriteControl_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPingableConn_WriteControl_Call) RunAndReturn(run func(messageType int, data []byte, deadline time.Time) error) *MockPingableConn_WriteControl_Call {
	_c.Call.Return(run)
	return _c
}
