package store_test

import (
	"strings"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	"github.com/sirupsen/logrus"
	"io"

	"github.com/kmacmcfarlane/checkpoint-sampler/backend/internal/store"
)

var _ = Describe("ComfyUIWSClient", func() {
	var logger *logrus.Logger

	BeforeEach(func() {
		logger = logrus.New()
		logger.SetOutput(io.Discard)
	})

	Describe("NewComfyUIWSClient", func() {
		It("creates a client", func() {
			client := store.NewComfyUIWSClient("http://localhost:8188", logger)
			Expect(client).NotTo(BeNil())
		})

		// AC: BE: WebSocket connection URL must include clientId so ComfyUI routes
		// prompt-specific events to this connection.
		It("generates a non-empty client ID", func() {
			client := store.NewComfyUIWSClient("http://localhost:8188", logger)
			Expect(client.GetClientID()).NotTo(BeEmpty())
		})

		It("generates a unique client ID for each new client", func() {
			client1 := store.NewComfyUIWSClient("http://localhost:8188", logger)
			client2 := store.NewComfyUIWSClient("http://localhost:8188", logger)
			Expect(client1.GetClientID()).NotTo(Equal(client2.GetClientID()))
		})
	})

	Describe("DeriveWebSocketURL", func() {
		DescribeTable("derives WebSocket URL from HTTP URL with clientId query parameter",
			func(httpURL string, clientID string, expectedWSURL string) {
				wsURL := store.DeriveWebSocketURL(httpURL, clientID)
				Expect(wsURL).To(Equal(expectedWSURL))
			},
			Entry("http to ws with clientId",
				"http://localhost:8188",
				"test-client-id",
				"ws://localhost:8188/ws?clientId=test-client-id",
			),
			Entry("https to wss with clientId",
				"https://comfyui.example.com",
				"my-client-id",
				"wss://comfyui.example.com/ws?clientId=my-client-id",
			),
			Entry("http with port to ws with port and clientId",
				"http://192.168.1.100:8188",
				"abc-123",
				"ws://192.168.1.100:8188/ws?clientId=abc-123",
			),
			Entry("https with port to wss with port and clientId",
				"https://comfyui.example.com:443",
				"def-456",
				"wss://comfyui.example.com:443/ws?clientId=def-456",
			),
			Entry("empty clientId produces URL without query parameter",
				"http://localhost:8188",
				"",
				"ws://localhost:8188/ws",
			),
		)

		// AC: BE: The client ID generated by NewComfyUIWSClient appears in the WS URL.
		It("includes the client ID from NewComfyUIWSClient in the connection URL", func() {
			client := store.NewComfyUIWSClient("http://localhost:8188", logger)
			clientID := client.GetClientID()
			Expect(clientID).NotTo(BeEmpty())

			// The WS URL (stored internally) should contain the clientId.
			// We verify indirectly: DeriveWebSocketURL with the same clientID produces a URL
			// that includes clientId=<uuid>.
			derivedURL := store.DeriveWebSocketURL("http://localhost:8188", clientID)
			Expect(strings.Contains(derivedURL, "clientId="+clientID)).To(BeTrue())
		})
	})
})
