package store_test

import (
	"context"
	"io"
	"net/http"
	"net/http/httptest"
	"strings"
	"sync/atomic"
	"time"

	"github.com/gorilla/websocket"
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	"github.com/sirupsen/logrus"

	"github.com/kmacmcfarlane/checkpoint-sampler/backend/internal/store"
)

var _ = Describe("ComfyUIWSClient", func() {
	var logger *logrus.Logger

	BeforeEach(func() {
		logger = logrus.New()
		logger.SetOutput(io.Discard)
	})

	Describe("NewComfyUIWSClient", func() {
		It("creates a client", func() {
			client := store.NewComfyUIWSClient("http://localhost:8188", logger)
			Expect(client).NotTo(BeNil())
		})

		// AC: BE: WebSocket connection URL must include clientId so ComfyUI routes
		// prompt-specific events to this connection.
		It("generates a non-empty client ID", func() {
			client := store.NewComfyUIWSClient("http://localhost:8188", logger)
			Expect(client.GetClientID()).NotTo(BeEmpty())
		})

		It("generates a unique client ID for each new client", func() {
			client1 := store.NewComfyUIWSClient("http://localhost:8188", logger)
			client2 := store.NewComfyUIWSClient("http://localhost:8188", logger)
			Expect(client1.GetClientID()).NotTo(Equal(client2.GetClientID()))
		})
	})

	Describe("DeriveWebSocketURL", func() {
		DescribeTable("derives WebSocket URL from HTTP URL with clientId query parameter",
			func(httpURL string, clientID string, expectedWSURL string) {
				wsURL := store.DeriveWebSocketURL(httpURL, clientID)
				Expect(wsURL).To(Equal(expectedWSURL))
			},
			Entry("http to ws with clientId",
				"http://localhost:8188",
				"test-client-id",
				"ws://localhost:8188/ws?clientId=test-client-id",
			),
			Entry("https to wss with clientId",
				"https://comfyui.example.com",
				"my-client-id",
				"wss://comfyui.example.com/ws?clientId=my-client-id",
			),
			Entry("http with port to ws with port and clientId",
				"http://192.0.2.100:8188",
				"abc-123",
				"ws://192.0.2.100:8188/ws?clientId=abc-123",
			),
			Entry("https with port to wss with port and clientId",
				"https://comfyui.example.com:443",
				"def-456",
				"wss://comfyui.example.com:443/ws?clientId=def-456",
			),
			Entry("empty clientId produces URL without query parameter",
				"http://localhost:8188",
				"",
				"ws://localhost:8188/ws",
			),
		)

		// AC: BE: The client ID generated by NewComfyUIWSClient appears in the WS URL.
		It("includes the client ID from NewComfyUIWSClient in the connection URL", func() {
			client := store.NewComfyUIWSClient("http://localhost:8188", logger)
			clientID := client.GetClientID()
			Expect(clientID).NotTo(BeEmpty())

			// The WS URL (stored internally) should contain the clientId.
			// We verify indirectly: DeriveWebSocketURL with the same clientID produces a URL
			// that includes clientId=<uuid>.
			derivedURL := store.DeriveWebSocketURL("http://localhost:8188", clientID)
			Expect(strings.Contains(derivedURL, "clientId="+clientID)).To(BeTrue())
		})
	})

	Describe("keepalive read deadline", func() {
		// AC: a dead/half-open ComfyUI connection is detected within a bounded
		// interval (deadline expiry) and triggers the disconnect handler.
		It("fires the disconnect handler when a silent peer stops responding", func() {
			// Stub WS server that upgrades the connection but never reads from
			// it. Because gorilla only replies to pings during a read, this
			// peer never sends a pong, so the client's read deadline expires.
			upgrader := websocket.Upgrader{}
			server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				conn, err := upgrader.Upgrade(w, r, nil)
				if err != nil {
					return
				}
				// Hold the connection open without reading, simulating a
				// half-open/dead peer.
				defer conn.Close()
				<-r.Context().Done()
			}))
			defer server.Close()

			client := store.NewComfyUIWSClient(server.URL, logger)
			// Short timings so the deadline expires quickly. pingInterval is
			// larger than pongWait so deadline expiry (not a ping write error)
			// is what drives the disconnect in this test.
			client.SetKeepaliveTimingsForTest(200*time.Millisecond, 150*time.Millisecond, 100*time.Millisecond)

			disconnected := make(chan struct{})
			var fired int32
			client.SetDisconnectHandler(func() {
				if atomic.CompareAndSwapInt32(&fired, 0, 1) {
					close(disconnected)
				}
			})

			Expect(client.Connect(context.Background())).To(Succeed())
			defer client.Close()

			Eventually(disconnected, 2*time.Second, 10*time.Millisecond).Should(BeClosed())
		})

		// AC: long idle periods on a HEALTHY connection (no execution events
		// for minutes) do NOT cause spurious disconnects (pong refreshes the
		// deadline).
		It("keeps a healthy connection alive past the deadline window via pong", func() {
			// Stub WS server that continuously reads. gorilla's default ping
			// handler replies with a pong on each read, which refreshes the
			// client's read deadline. The server never sends data events,
			// simulating a long GPU-bound generation.
			upgrader := websocket.Upgrader{}
			server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				conn, err := upgrader.Upgrade(w, r, nil)
				if err != nil {
					return
				}
				defer conn.Close()
				for {
					if _, _, err := conn.ReadMessage(); err != nil {
						return
					}
				}
			}))
			defer server.Close()

			client := store.NewComfyUIWSClient(server.URL, logger)
			// Ping faster than the pongWait so pongs keep refreshing the
			// deadline. The healthy window we assert (300ms) far exceeds
			// pongWait (100ms), proving pongs—not silence—keep it alive.
			client.SetKeepaliveTimingsForTest(40*time.Millisecond, 100*time.Millisecond, 50*time.Millisecond)

			var fired int32
			client.SetDisconnectHandler(func() {
				atomic.StoreInt32(&fired, 1)
			})

			Expect(client.Connect(context.Background())).To(Succeed())
			defer client.Close()

			// Across multiple pongWait windows the connection must stay up.
			Consistently(func() int32 {
				return atomic.LoadInt32(&fired)
			}, 300*time.Millisecond, 20*time.Millisecond).Should(BeZero())
		})
	})
})
