// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package servicemocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockSampleDirRemover creates a new instance of MockSampleDirRemover. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSampleDirRemover(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSampleDirRemover {
	mock := &MockSampleDirRemover{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSampleDirRemover is an autogenerated mock type for the SampleDirRemover type
type MockSampleDirRemover struct {
	mock.Mock
}

type MockSampleDirRemover_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSampleDirRemover) EXPECT() *MockSampleDirRemover_Expecter {
	return &MockSampleDirRemover_Expecter{mock: &_m.Mock}
}

// RemoveCheckpointOutputDir provides a mock function for the type MockSampleDirRemover
func (_mock *MockSampleDirRemover) RemoveCheckpointOutputDir(trainingRunName string, studyName string, checkpointFilename string) error {
	ret := _mock.Called(trainingRunName, studyName, checkpointFilename)

	if len(ret) == 0 {
		panic("no return value specified for RemoveCheckpointOutputDir")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = returnFunc(trainingRunName, studyName, checkpointFilename)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSampleDirRemover_RemoveCheckpointOutputDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveCheckpointOutputDir'
type MockSampleDirRemover_RemoveCheckpointOutputDir_Call struct {
	*mock.Call
}

// RemoveCheckpointOutputDir is a helper method to define mock.On call
//   - trainingRunName string
//   - studyName string
//   - checkpointFilename string
func (_e *MockSampleDirRemover_Expecter) RemoveCheckpointOutputDir(trainingRunName any, studyName any, checkpointFilename any) *MockSampleDirRemover_RemoveCheckpointOutputDir_Call {
	return &MockSampleDirRemover_RemoveCheckpointOutputDir_Call{Call: _e.mock.On("RemoveCheckpointOutputDir", trainingRunName, studyName, checkpointFilename)}
}

func (_c *MockSampleDirRemover_RemoveCheckpointOutputDir_Call) Run(run func(trainingRunName string, studyName string, checkpointFilename string)) *MockSampleDirRemover_RemoveCheckpointOutputDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSampleDirRemover_RemoveCheckpointOutputDir_Call) Return(err error) *MockSampleDirRemover_RemoveCheckpointOutputDir_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSampleDirRemover_RemoveCheckpointOutputDir_Call) RunAndReturn(run func(trainingRunName string, studyName string, checkpointFilename string) error) *MockSampleDirRemover_RemoveCheckpointOutputDir_Call {
	_c.Call.Return(run)
	return _c
}
