// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package servicemocks

import (
	"context"

	"github.com/kmacmcfarlane/checkpoint-sampler/backend/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockObjectInfoGetter creates a new instance of MockObjectInfoGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObjectInfoGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObjectInfoGetter {
	mock := &MockObjectInfoGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockObjectInfoGetter is an autogenerated mock type for the ObjectInfoGetter type
type MockObjectInfoGetter struct {
	mock.Mock
}

type MockObjectInfoGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObjectInfoGetter) EXPECT() *MockObjectInfoGetter_Expecter {
	return &MockObjectInfoGetter_Expecter{mock: &_m.Mock}
}

// GetObjectInfo provides a mock function for the type MockObjectInfoGetter
func (_mock *MockObjectInfoGetter) GetObjectInfo(ctx context.Context, nodeType string) (*model.ObjectInfo, error) {
	ret := _mock.Called(ctx, nodeType)

	if len(ret) == 0 {
		panic("no return value specified for GetObjectInfo")
	}

	var r0 *model.ObjectInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.ObjectInfo, error)); ok {
		return returnFunc(ctx, nodeType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.ObjectInfo); ok {
		r0 = returnFunc(ctx, nodeType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ObjectInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, nodeType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObjectInfoGetter_GetObjectInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObjectInfo'
type MockObjectInfoGetter_GetObjectInfo_Call struct {
	*mock.Call
}

// GetObjectInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - nodeType string
func (_e *MockObjectInfoGetter_Expecter) GetObjectInfo(ctx any, nodeType any) *MockObjectInfoGetter_GetObjectInfo_Call {
	return &MockObjectInfoGetter_GetObjectInfo_Call{Call: _e.mock.On("GetObjectInfo", ctx, nodeType)}
}

func (_c *MockObjectInfoGetter_GetObjectInfo_Call) Run(run func(ctx context.Context, nodeType string)) *MockObjectInfoGetter_GetObjectInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObjectInfoGetter_GetObjectInfo_Call) Return(objectInfo *model.ObjectInfo, err error) *MockObjectInfoGetter_GetObjectInfo_Call {
	_c.Call.Return(objectInfo, err)
	return _c
}

func (_c *MockObjectInfoGetter_GetObjectInfo_Call) RunAndReturn(run func(ctx context.Context, nodeType string) (*model.ObjectInfo, error)) *MockObjectInfoGetter_GetObjectInfo_Call {
	_c.Call.Return(run)
	return _c
}
